$(document).ready(function(){
  var PS = "Personal Service";
  var PSDescription = "Phone - Web Chat - Email";
  var FS = "Free UK Delivery";
  var FSDescription = "When you spend over £29";
  var WWD = "World Wide Delivery";
  var WWDDescription = "We ship globally";
  var ER = "Easy Returns";
  var ERDescription = "No quibble returns";

  var finalCode = '<div class="container header-usp-container"><ul class="usp-list"><li class="usp-list-item first-usp show"><p class="usp-element"><img class="show lazyautosizes ls-is-cached lazyloaded" data-sizes="auto" src="https://cdn11.bigcommerce.com/s-pvnu6go698/product_images/uploaded_images/f-shipping.png" data-src="https://cdn11.bigcommerce.com/s-pvnu6go698/product_images/uploaded_images/f-shipping.png" alt="Personal Service" title="Personal Service" sizes="53px"><span class="usp-content show"><label class="usp-content-main">'+PS+'</label><label class="usp-content-sub">'+PSDescription+'</label></span></p></li><li class="usp-list-item second-usp show"><p class="usp-element"><img class="show lazyautosizes ls-is-cached lazyloaded" data-sizes="auto" src="https://cdn11.bigcommerce.com/s-pvnu6go698/product_images/uploaded_images/f-exchange.png" data-src="https://cdn11.bigcommerce.com/s-pvnu6go698/product_images/uploaded_images/f-exchange.png" alt="Free UK Delivery" title="Free UK Delivery" sizes="34px"><span class="usp-content show"><label class="usp-content-main">'+FS+'</label><label class="usp-content-sub">'+FSDescription+'</label></span></p></li><li class="usp-list-item third-usp show"><p class="usp-element"><img class="show lazyautosizes ls-is-cached lazyloaded" data-sizes="auto" src="https://cdn11.bigcommerce.com/s-pvnu6go698/product_images/uploaded_images/f-secure.png" data-src="https://cdn11.bigcommerce.com/s-pvnu6go698/product_images/uploaded_images/f-secure.png" alt="World Wide Delivery" title="World Wide Delivery" sizes="39px"><span class="usp-content show"><label class="usp-content-main">'+WWD+'</label><label class="usp-content-sub">'+WWDDescription+'</label></span></p></li><li class="usp-list-item fourth-usp show"><p class="usp-element"><img class="show lazyautosizes ls-is-cached lazyloaded" data-sizes="auto" src="https://cdn11.bigcommerce.com/s-pvnu6go698/product_images/uploaded_images/f-amazing.png" data-src="https://cdn11.bigcommerce.com/s-pvnu6go698/product_images/uploaded_images/f-amazing.png" alt="Easy Returns" title="Easy Returns" sizes="31px"><span class="usp-content show"><label class="usp-content-main">'+ER+'</label><label class="usp-content-sub">'+ERDescription+'</label></span></p></li></ul></div>';
});
